task1
mipt-diht/mipt-latex-fall2018-Ekateriner pull request #1
Opened 2018-10-25 15:25 UTC by Ekateriner

Yushina Ekaterina

2018-10-25 15:55 UTC, AShepelevv requested changes

2018-10-25 15:55 UTC, AShepelevv commented on task1/task1.tex
> +	\normalsize Для \textit{плоского} треугольника со сторонами $a, b, c$ и углом $\alpha,$ лежащим против стороны $a,$ справедливо соотношение
Наклонный, а не курсив.

2018-10-25 15:55 UTC, AShepelevv commented on task1/task1.tex
> +	\vspace{1cm}
В pdf нет этого отступа.

2018-10-25 15:55 UTC, AShepelevv commented on task1/task1.tex
> +	\normalsize Для \textit{плоского} треугольника со сторонами $a, b, c$ и углом $\alpha,$ лежащим против стороны $a,$ справедливо соотношение
Зачем `\normalsize`? Когда можно было область видимости для заголовка сделать?

2018-10-25 15:55 UTC, AShepelevv commented on task1/task1.tex
> +	\normalsize Для \textit{плоского} треугольника со сторонами $a, b, c$ и углом $\alpha,$ лежащим против стороны $a,$ справедливо соотношение
`$a, b, c$` пробелы игнорируются в формулах, а на печати они должны быть. Каждую букву нужно писать отдельно.

2018-10-25 15:55 UTC, AShepelevv commented on task1/task1.tex
> +	А теперь формулы. ФОРМУЛА~--- краткое и точное словестное выражение, определение или же ряд математических величин, выраженный условными знаками.
Не капсом, а заглавным начертанием.

2018-10-25 15:55 UTC, AShepelevv commented on task1/task1.tex
> +	    Это мой первый документ в системе компьютерной верстки \LaTeX \\
Эта строчка не должна быть по центру, просто слег абзацный отступ, а выравнивание стандартное.

2018-10-25 15:55 UTC, AShepelevv commented on task1/task1.tex
> +	\normalsize Для \textit{плоского} треугольника со сторонами $a, b, c$ и углом $\alpha,$ лежащим против стороны $a,$ справедливо соотношение
А можно `\LARGE\textbf` два раза не повторять?

2018-10-25 15:55 UTC, AShepelevv commented on task1/task1.tex
> +	\normalsize Для \textit{плоского} треугольника со сторонами $a, b, c$ и углом $\alpha,$ лежащим против стороны $a,$ справедливо соотношение
Знаки препинания по возможности нужно выносить из формул.

2018-10-25 15:55 UTC, AShepelevv commented on task1/task1.tex
> +	\hspace{28pt} \LARGE\textbf{Термодинамика} \par
Тут отступ не 28pt, а 28pt + абзацный, а должно быть просто 28pt

2018-10-25 15:55 UTC, AShepelevv commented on task1/task1.tex
> +	\hspace{28pt} \LARGE\textbf{Геометрия} \hfill\LARGE\textbf{Планеметрия} \par
Тут отступ не 28pt, а 28pt + абзацный, а должно быть просто 28pt

2018-10-29 14:41 UTC, AShepelevv commented
@Ekateriner, собираешься что-нибудь исправлять?

2018-10-29 14:41 UTC, AShepelevv requested changes

2018-10-29 14:41 UTC, AShepelevv commented on task1/task1.tex
> +	    \Huge {<<УРА!!!>>}
Без засечек в примере.

2018-10-29 16:15 UTC, Ekateriner commented
Я исправлю, просто до этого почту не чекала(

2018-10-29 21:13 UTC, Ekateriner commented
На счет отступов, я попыталась их справить, но что-то мне подсказывает, что не особо получилось, и я честно не совсем понимаю как это работает

2018-10-30 15:01 UTC, AShepelevv requested changes

2018-10-30 15:01 UTC, AShepelevv commented on task1/task1.tex
> +	А теперь формулы. \textsc{формула}~--- краткое и точное словестное выражение, определение или же ряд математических величин, выраженный условными знаками.\\[15pt]
Формула в примере написана с большой буквы.

2018-10-30 15:01 UTC, merged

2018-10-30 15:03 UTC, AShepelevv commented
Кажется, достаточно использовать `\hspace*{}` в совчетании с `\vspace{}`. И при этом не оставлять пустых строк. Тогда абзацного отступа не будет.

2018-10-30 15:04 UTC, AShepelevv commented
Сойдемся на 9.